export const data = [
  {
    id: 1,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'https://vjs.zencdn.net/v/oceans.mp4',
    likes: 302,
    comments: 26,
  },
  {
    id: 2,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'https://picsum.photos/200/300',
    likes: 302,
    comments: 26,
  },
  {
    id: 3,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    likes: 302,
    comments: 26,
  },
  {
    id: 4,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'https://media.idownloadblog.com/wp-content/uploads/2016/02/Twitter-GIF.gif',
    likes: 302,
    comments: 26,
  },
  {
    id: 5,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'https://picsum.photos/id/2/200/300',
    likes: 302,
    comments: 26,
  },
  {
    id: 6,
    logo: 'https://reactnative.dev/img/tiny_logo.png',
    title: 'r/reactnative',
    sub_title: 'u/TomatoSlasher',
    description: 'Location-based AR game built with react native',
    post: 'https://media.giphy.com/media/tbRxcDexnNJvlYckWU/giphy.gif?cid=ecf05e47n4tf886jfttcwc1k121auvy8o2gdhse49wtechbk&rid=giphy.gif&ct=g',
    likes: 302,
    comments: 26,
  },
];
